package net.royling.lovelysparklepieces.datagenerator;

import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.client.model.generators.ItemModelProvider;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import net.royling.lovelysparklepieces.LovelySparklePieces;
import net.royling.lovelysparklepieces.ModItem.ModCurios.ModCurios;
import net.royling.lovelysparklepieces.ModItem.ModUsingItem.ModItems;

public class ModItemModelProvider extends ItemModelProvider{
    public ModItemModelProvider(PackOutput output, ExistingFileHelper existingFileHelper) {
        super(output, LovelySparklePieces.MODID, existingFileHelper);
    }

    @Override
    protected void registerModels() {
        basicItem(ModCurios.MAGNETIC_RING.get());
        basicItem(ModCurios.SUPER_MAGNETIC_RING.get());
        basicItem(ModCurios.BLASPHEMOUS_CONTRACT.get());
        basicItem(ModCurios.ENCHANT_EYE.get());
        basicItem(ModCurios.ENDER_RING.get());
        basicItem(ModCurios.CRIT_RING.get());
        basicItem(ModCurios.MEMORY_RING.get());
        basicItem(ModCurios.NIGHT_OWL_RING.get());
        basicItem(ModCurios.FPS_EYE.get());
        basicItem(ModCurios.CAT_BOOT.get());
        basicItem(ModCurios.GOAT_BOOT.get());
        basicItem(ModCurios.RABBIT_BOOT.get());
        basicItem(ModCurios.FOX_BOOT.get());
        basicItem(ModCurios.SOUL_QUIVER.get());
        basicItem(ModCurios.BLACKSTONE_HEART.get());
        basicItem(ModCurios.MAGMA_AMULET.get());
        basicItem(ModCurios.MOON_AMULET.get());
        basicItem(ModCurios.STRAW_SANDALS.get());
        basicItem(ModCurios.CRYSTAL_BOOT.get());
        basicItem(ModCurios.BLADE_BOOT.get());
        basicItem(ModCurios.GUARD_BOOT.get());
        basicItem(ModCurios.WARRIOR_GREAVES.get());
        basicItem(ModCurios.FLOWER_BOOT.get());
        basicItem(ModCurios.WATERWALK_BOOT.get());
        basicItem(ModCurios.GAMBLERS_POKER.get());
        basicItem(ModCurios.GAMBLERS_GOLD_COIN.get());
        basicItem(ModCurios.GAMBLERS_EARRINGS.get());
        basicItem(ModCurios.GAMBLERS_DICE.get());
        basicItem(ModCurios.GAMBLERS_CORSAGE.get());
        basicItem(ModCurios.NEWBIE_UMBRELLA.get());
        basicItem(ModCurios.BLAZE_CORE.get());
        basicItem(ModCurios.RESUSCITATOR.get());
        basicItem(ModCurios.ROLLER_SKATES.get());
        basicItem(ModCurios.CRUSH_STONE_RING.get());
        basicItem(ModCurios.INFERNO_RING.get());
        basicItem(ModCurios.ECO_RING.get());
        basicItem(ModCurios.BONE_ARMOR.get());
        basicItem(ModCurios.VOID_TENTACLES.get());
        basicItem(ModCurios.DISASTER_EMBLEM.get());
        basicItem(ModCurios.THE_EVIL_CURSE.get());

        basicItem(ModCurios.NIGHT_VISION.get());
        basicItem(ModCurios.JELLYFISH_HELMET.get());
        basicItem(ModCurios.CAPITALIST_HEAT.get());
        basicItem(ModCurios.POSEIDON_RESPIRATOR.get());
        basicItem(ModCurios.EYE_MASK.get());
        basicItem(ModCurios.MARKSMAN_GOGGLES.get());
        basicItem(ModCurios.YELLOW_HEADSCARF.get());
        basicItem(ModCurios.HEAVY_BIGROCK.get());
        basicItem(ModCurios.POCKET_WATCH.get());
        basicItem(ModCurios.MERMAID_TAIL.get());
        basicItem(ModCurios.JUMPING_FOOTWEAR.get());
        basicItem(ModCurios.WIND_LEAP_BOOTS.get());
        basicItem(ModCurios.SKY_BEAST_SHOES.get());
        basicItem(ModCurios.DRAGON_HEART.get());
        basicItem(ModCurios.DOUBLE_NIGHT_VISION.get());
        basicItem(ModCurios.QUARTER_NIGHT_VISION.get());
        basicItem(ModCurios.LEATHER_QUIVER.get());
        basicItem(ModCurios.SPEEDOMETER.get());
        basicItem(ModCurios.POSITION_TRACKER.get());
        basicItem(ModCurios.GPS.get());
        basicItem(ModCurios.HIGH_QUALITY_FISHING_LINE.get());
        basicItem(ModCurios.WOOD_GRAIN_QUIVER.get());
        basicItem(ModCurios.PDA.get());
        basicItem(ModCurios.MIRROR_AND_WATER.get());
        basicItem(ModCurios.GOLDEN_HOOK.get());
        basicItem(ModCurios.ADVENTURER_BELT.get());
        basicItem(ModCurios.SLIME_EATER.get());
        basicItem(ModCurios.GLUTTONY_AMULET.get());
        basicItem(ModCurios.POWER_AMULET.get());
        basicItem(ModCurios.MYSTERIOUS_GEL.get());
        basicItem(ModCurios.ERODED_FACE.get());
        basicItem(ModCurios.UFFFD.get());
        basicItem(ModCurios.EMBER_CORE.get());
        basicItem(ModCurios.SOUL_MARK.get());
        basicItem(ModCurios.VALORANT.get());
        basicItem(ModCurios.PUREGOLD_RING.get());
        basicItem(ModCurios.BASTION_RING.get());
        basicItem(ModCurios.CREEPFEAR_AMULET.get());
        basicItem(ModCurios.BABY_FEEDER.get());
        basicItem(ModCurios.GILDED_PIPE.get());
        basicItem(ModCurios.AMULET_POUCH.get());
        basicItem(ModCurios.FISHERMAN_TOOLBOX.get());
        basicItem(ModCurios.DOUBLE_HOOK.get());
        basicItem(ModCurios.GREAT_SHIFT.get());
        basicItem(ModCurios.DREAM_HEART.get());
        basicItem(ModCurios.ROFAP.get());
        basicItem(ModCurios.TWILIGHT_MOMENT.get());
        basicItem(ModCurios.MOONLIGHT_BRACELET.get());
        basicItem(ModCurios.VERSATILE_PERSON.get());
        //
        handheldItem(ModItems.SOUL_TORCH.get());
        handheldItem(ModItems.NECROPSYCHE_PAPILLON.get());
        basicItem(ModItems.DOMAIN_STONE.get());
        handheldItem(ModItems.FIREBALL_STAFF.get());
        handheldItem(ModItems.POLYMERIZATION.get());
        handheldItem(ModItems.SUPERPOLYMERIZATION.get());
        basicItem(ModItems.FISHING_TREASURE.get());
        handheldItem(ModItems.PIRATE_SCIMITAR.get());
        handheldItem(ModItems.FISH_HOE.get());
        handheldItem(ModItems.FISH_AXE.get());
        handheldItem(ModItems.FISH_PICKAXE.get());
        handheldItem(ModItems.FISH_SHOVEL.get());
        handheldItem(ModItems.HELL_FIRE.get());
        handheldItem(ModItems.LUCY_AXE.get());
        handheldItem(ModItems.GRAVEDIGGER.get());
        basicItem(ModItems.MOJA_COLA.get());
        basicItem(ModItems.FLINTLOCK_BULLET.get());
        basicItem(ModItems.BATTERY.get());
        basicItem(ModItems.INFINITE_APPLE.get());
        basicItem(ModItems.MULTI_PURPOSE_TOOL.get());
        basicItem(ModItems.CAPITALIST_CAKE.get());
        basicItem(ModItems.SPARKLE_SHARD.get());
        basicItem(ModItems.MOON_INGOT.get());
        basicItem(ModItems.ABIGAILS_FLOWER.get());
    }
}
